on:
  push:
    branches:
      - changePassword

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
      - name: Download Gradle Wrapper
        run: ./gradlew wrapper --gradle-version 7.1
      - name: Build
        run: |
          ./gradlew clean build -Porg.gradle.java.home=$JAVA_HOME

          plugins {
            id 'java'
            id 'org.springframework.boot' version '3.0.6'
            id 'io.spring.dependency-management' version '1.1.0'
          }

          group = 'nl.sogyo'
          version = '0.0.1-SNAPSHOT'
          sourceCompatibility = '17'

          repositories {
            mavenCentral()
          }

          dependencies {
            implementation 'org.springframework.boot:spring-boot-starter'
            implementation 'org.jetbrains:annotations:24.0.0'
            testImplementation 'org.springframework.boot:spring-boot-starter-test'
            // testImplementation group: 'com.h2database', name: 'h2', version: '1.3.164'
            implementation 'org.springframework.boot:spring-boot-starter-web'
            implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
            implementation 'org.hibernate:hibernate-entitymanager:5.6.15.Final'
            implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
            implementation group: 'com.mysql', name: 'mysql-connector-j', version: '8.0.33'
            implementation group: 'org.springframework.boot', name: 'spring-boot-starter-aop', version: '1.2.3.RELEASE'
          }

          tasks.named('test') {
            useJUnitPlatform()
          }


#   unit-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Unit Tests
#         run: |
#           echo "Running unit tests... This will take about 60 seconds."
#           sleep 1
#           echo "Code coverage is 90%"

#   lint-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Lint Tests
#         run: |
#           echo "Linting code... This will take about 10 seconds."
#           sleep 1
#           echo "No lint issues found."

#   deploy-job:
#     runs-on: ubuntu-latest
#     needs: [unit-test-job, lint-test-job]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Deploy to Azure
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: bankappip
#           publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
