# Workflow name
name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
      - name: Build with Gradle
        uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
        with:
          arguments: build

#   unit-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Unit Tests
#         run: |
#           echo "Running unit tests... This will take about 60 seconds."
#           sleep 1
#           echo "Code coverage is 90%"

#   lint-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Lint Tests
#         run: |
#           echo "Linting code... This will take about 10 seconds."
#           sleep 1
#           echo "No lint issues found."

#   deploy-job:
#     runs-on: ubuntu-latest
#     needs: [unit-test-job, lint-test-job]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Deploy to Azure
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: bankappip
#           publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
