name: CI/CD Pipeline

on:
  push:
    branches:
      - changePassword

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          echo "Compiling the code..."
          echo "Compile complete."

  unit-test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Unit Tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          sleep 1
          echo "Code coverage is 90%"

  lint-test-job:
    runs-on: ubuntu-latest
    needs: build-job
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint Tests
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 1
          echo "No lint issues found."

  deploy-job:
    runs-on: ubuntu-latest
    needs: [unit-test-job, lint-test-job]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Azure
        uses: azure/webapps-deploy@v2
        with:
          app-name: bankappip
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
