# Workflow name
name: CI/CD Pipeline

on:
  push:
    branches:
      - changePassword

jobs:
  # Test job
  tests:
    name: Unit tests
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest
    # Job's steps
    steps:
      # Check-out your repository under $GITHUB_WORKSPACE, so your workflow can access it
      - uses: actions/checkout@v2
      
      # Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
      
      # Run Gradle build
      - name: Run Gradle Build
        run: ./gradlew clean build --no-daemon





#   unit-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Unit Tests
#         run: |
#           echo "Running unit tests... This will take about 60 seconds."
#           sleep 1
#           echo "Code coverage is 90%"

#   lint-test-job:
#     runs-on: ubuntu-latest
#     needs: build-job
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Lint Tests
#         run: |
#           echo "Linting code... This will take about 10 seconds."
#           sleep 1
#           echo "No lint issues found."

#   deploy-job:
#     runs-on: ubuntu-latest
#     needs: [unit-test-job, lint-test-job]
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3
#       - name: Setup JDK
#         uses: actions/setup-java@v2
#         with:
#           java-version: 11
#       - name: Deploy to Azure
#         uses: azure/webapps-deploy@v2
#         with:
#           app-name: bankappip
#           publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
